name: Create a Sentry release
on:
  push:
    branches:
      - 'master'
jobs:
  create-sentry-release:
    uses: ./.github/workflows/core/create-sentry-release.yml
    with:
      project: stamp
    secrets: inherit
